version: 2

sources:
  - name: raw_ingestion
    description: A sample of metadata from songs played on Spotify in 2023.
    database: storied-storm-353916
    schema: raw_ingestion
    tables:
      - name: spotify_top_2023_metadata
